- name: extending existing LVM volume group
  lvg:
    vg: "{{ vgname }}"
    pvs: "{{ extend_disks }}"
  when: extend and config_lvm

- name: extending existing filesystem
  command: lvextend {{ lvextend_options }} /dev/{{ vgname }}/{{ lvname }}
  when: extend and config_lvm

- name: resizing filesystem
  command: xfs_growfs /dev/{{ vgname }}/{{ lvname }}
  when: resize and config_lvm